### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by nicolas-sabbatini** [maciekglowka/hike_deck#3]
Hi! I came across your tutorial on [This Month in Rust GameDev #45](https://gamedev.rs/news/045/#bevy-roguelike-tutorial) and found it really interesting. I started following the tutorial and adding my own spin to it, but I started to have questions about the tutorial license.

Could you please let me know what license the project is released under? It would be greatly appreciated if you could provide some information regarding the permissions and restrictions associated with the tutorial's license.

**Comment by maciekglowka** [comment]
Hi, thanks for checking the tutorial. I'm glad it is somehow useful :)
The tutorial code can be freely used, so I guess the MIT license should be permissive enough (not an expert here).

I've added the info already to the main branch.
